INSERT INTO categories
  (slug, name_zh, name_en, summary_zh, summary_en, medium_zh, medium_en, focus_zh, focus_en, cover_url, accent, sort_order, is_active)
VALUES
  ('chinese-painting', '中国画', 'Chinese Painting', '以笔墨、气韵和留白构成的观看方式，在墨色浓淡之间建立精神的空间。', 'A way of seeing built from brush, ink, rhythm, and emptiness, where spiritual space appears through tonal depth.', '水墨 / 工笔 / 人物 / 山水', 'Ink / Wash / Figure / Landscape', '笔墨秩序、空间留白、意境生成', 'Brush order, negative space, atmosphere', 'https://imgbed.698891.xyz/file/logo/maxae/ChinesePainting/1778989480481_27576_1024_.jpg', '#c084fc', 10, 1),
  ('oil-painting', '油画', 'Oil Painting', '颜料的厚度、光线的层次与画面的时间感，共同构成油画的可视重量。', 'Pigment thickness, light, and pictorial time give painting its visible weight and emotional density.', '油彩 / 丙烯 / 具象 / 抽象', 'Oil / Acrylic / Figurative / Abstract', '色彩层次、光感、画面结构', 'Color layers, light, pictorial structure', 'https://imgbed.698891.xyz/file/logo/maxae/OilPainting/1778991136054_pexels-photo-5203636.jpeg', '#facc15', 20, 1),
  ('printmaking', '版画', 'Printmaking', '在压力、刻痕与复数之间，版画把材料的痕迹转化为图像的秩序。', 'Between pressure, incision, and edition, printmaking turns material trace into pictorial order.', '木刻 / 铜版 / 石版 / 丝网', 'Woodcut / Intaglio / Lithography / Screenprint', '痕迹、压印、复数与版本', 'Trace, pressure, edition, matrix', 'https://imgbed.698891.xyz/file/logo/maxae/Printmaking/1778991775952_pexels-photo-36098334.jpeg', '#c084fc', 30, 1),
  ('sculpture', '雕塑', 'Sculpture', '雕塑把重量、体量和空间关系变成可绕行的观看经验。', 'Sculpture turns weight, volume, and spatial relation into an experience that can be walked around.', '石材 / 金属 / 木材 / 陶土', 'Stone / Metal / Wood / Clay', '体量、重量、空间和触感', 'Volume, weight, space, tactility', 'https://imgbed.698891.xyz/file/logo/maxae/Sculpture/1778991252006_pexels-photo-4195626.jpeg', '#facc15', 40, 1),
  ('mural-painting', '壁画', 'Mural Painting', '壁画以墙面为载体，让图像和建筑、场域与公共记忆发生关系。', 'Mural painting uses the wall as its support, linking image with architecture, site, and public memory.', '墙面绘画 / 公共艺术 / 湿壁画', 'Wall Painting / Public Art / Fresco', '场域、尺度、公共性', 'Site, scale, public presence', 'https://imgbed.698891.xyz/file/logo/maxae/MuralPainting/1778996646575_image.png', '#c084fc', 50, 1),
  ('drawing', '素描', 'Drawing', '素描以最直接的线条记录观察，在黑白、明暗和结构中训练视觉的判断力。', 'Drawing records observation through direct line, training visual judgment through tone, structure, and proportion.', '速写 / 炭笔 / 石墨 / 墨', 'Sketch / Charcoal / Graphite / Ink', '线条、结构、明暗和观察', 'Line, structure, tone, observation', 'https://imgbed.698891.xyz/file/logo/maxae/Drawing/1778991599540_pexels-photo-7608653.jpeg', '#facc15', 60, 1),
  ('calligraphy', '书法', 'Calligraphy', '书法在笔势、节奏与结体中展开，把文字的意义推向身体与时间。', 'Calligraphy unfolds through gesture, rhythm, and structure, extending written meaning into body and time.', '书体 / 篆刻 / 题跋 / 水墨', 'Script / Seal / Inscription / Ink', '笔势、结体、节奏和气息', 'Gesture, structure, rhythm, breath', 'https://imgbed.698891.xyz/file/logo/maxae/Calligraphy/1778989600680_17170_1024_.jpg', '#c084fc', 70, 1),
  ('watercolor-pastel', '水彩与粉画', 'Watercolor & Pastel', '水彩与粉画以透明、颗粒和纸面吸附为语言，在轻盈中留住瞬间。', 'Watercolor and pastel speak through transparency, grain, and paper absorption, holding the instant in lightness.', '水彩 / 水粉 / 色粉 / 纸本', 'Watercolor / Gouache / Pastel / Paper', '透明度、颗粒、纸感和色层', 'Transparency, grain, paper, color layers', 'https://imgbed.698891.xyz/file/logo/maxae/WatercolorPastel/1778995327832_pexels-photo-24783388.jpeg', '#facc15', 80, 1),
  ('mixed-media', '综合材料艺术', 'Mixed Media', '综合材料把平面、物件、背景和痕迹放在一起，让材料本身参与叙事。', 'Mixed media brings surface, object, background, and trace together, allowing material itself to enter the narrative.', '拼贴 / 装配 / 材料 / 物件', 'Collage / Assemblage / Material / Object', '层叠、物性、组合和语境', 'Layering, materiality, assembly, context', 'https://imgbed.698891.xyz/file/logo/maxae/MixedMedia/1778996173874_photo-1604871000636-074fa5117945', '#c084fc', 90, 1)
ON CONFLICT(slug) DO UPDATE SET
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  cover_url = excluded.cover_url,
  updated_at = CURRENT_TIMESTAMP;
